version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5002:5002
      - 443:443
    restart: always
    networks:
      backend:

networks:
  backend:
    driver: overlay
    external: true
