version: "3.9"
services:
  mysql-master:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_RANDOM_PASSWORD: P@ssw0rd
    networks:
        cluster:
            ipv4_address: 192.169.1.102

  mysql-node1:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_RANDOM_PASSWORD: P@ssw0rd
    networks:
        cluster:
            ipv4_address: 192.169.1.104

  mysql-node2:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_RANDOM_PASSWORD: P@ssw0rd
    networks:
        cluster:
            ipv4_address: 192.169.1.105

networks:
  cluster:
    driver: bridge
