version: "3.9"
name: kafka
x-common-extra-hosts: &common-extra-hosts
  extra_hosts:
    - "qualidade-db-ces.azores.gov.pt:192.168.1.10"
    - "qualidade-redis-ces.azores.gov.pt:192.168.1.20"
    - "qualidade-es01-ces.azores.gov.pt:192.168.1.30"
    - "qualidade-kafka1-ces.azores.gov.pt:192.168.1.50"
    - "qualidade-fe-ces.azores.gov.pt:192.168.1.80"
    - "qualidade-api-ces.azores.gov.pt:192.168.1.90"
    
services:
  zookeeper1:
    container_name: zookeeper1
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
        babel-network:
            ipv4_address: 192.168.1.50

  kafka1:
    container_name: kafka1
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper1
    ports:
      - 19092:19092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://kafka1:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
        babel-network:
            ipv4_address: 192.168.1.60
    volumes:
      - kafka1_data:/var/lib/kafka/data

  kafka2:
    container_name: kafka2
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper1
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092,PLAINTEXT_HOST://kafka1:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
        babel-network:
            ipv4_address: 192.168.1.70
    volumes:
      - kafka2_data:/var/lib/kafka/data

 


volumes:
  kafka1_data:
  kafka2_data:

   
networks:
  babel-network:
    name: babel-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24