CREATE USER IF NOT EXISTS 'CESUser'@'%' IDENTIFIED BY 'tj17txxk3FUC';

GRANT ALL privileges ON *.* TO 'CESUser'@'%' with grant option;

-- reset master;


-- CREATE DB

CREATE DATABASE IF NOT EXISTS `CES.API.Database`;
CREATE DATABASE IF NOT EXISTS `CES.API.Log`;

USE `CES.API.Database`;

CREATE USER IF NOT EXISTS 'CESUser'@'%' IDENTIFIED BY 'tj17txxk3FUC';
GRANT ALL PRIVILEGES ON `CES.API.Database`.* TO 'CESUser'@'%';
GRANT ALL PRIVILEGES ON `CES.API.Log`.* TO 'CESUser'@'%';