version: "3.9"
name: elasticsearch-es02
x-common-extra-hosts: &common-extra-hosts
  extra_hosts:
    - "qualidade-db-ces.azores.gov.pt:192.168.1.10"
    - "qualidade-redis-ces.azores.gov.pt:192.168.1.20"
    - "qualidade-es01-ces.azores.gov.pt:192.168.1.30"
    - "qualidade-es02-ces.azores.gov.pt:192.168.1.31"
    - "qualidade-kafka1-ces.azores.gov.pt:192.168.1.50"
    - "qualidade-fe-ces.azores.gov.pt:192.168.1.80"
    - "qualidade-api-ces.azores.gov.pt:192.168.1.90"
    
services:
  es02:
    container_name: es02
    env_file:
      - ./ElasticSearch/es02/ElasticSearchEnvironment.env
    hostname: qualidade-es02-ces.azores.gov.pt
    build:
      context: .
      dockerfile: ./ElasticSearch/es02/ElasticSearchDockerfile
    networks:
      babel-network:
        ipv4_address: 192.168.1.31
    ports:
      - 9201:9200
#      - 9300:9300
    <<: *common-extra-hosts
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es02_data:/usr/share/elasticsearch/data
volumes:
  es02_data:

networks:
  babel-network:
    external: true
    driver: overlay  