version: "3.9"
name: elasticsearch-es01
x-common-extra-hosts: &common-extra-hosts
  extra_hosts:
    - "qualidade-db-ces.azores.gov.pt:192.168.1.10"
    - "qualidade-redis-ces.azores.gov.pt:192.168.1.20"
    - "qualidade-es01-ces.azores.gov.pt:192.168.1.30"
    - "qualidade-es02-ces.azores.gov.pt:192.168.1.31"
    - "qualidade-kafka1-ces.azores.gov.pt:192.168.1.50"
    - "qualidade-fe-ces.azores.gov.pt:192.168.1.80"
    - "qualidade-api-ces.azores.gov.pt:192.168.1.90"
    
services:
  es01:
    container_name: es01
    env_file:
      - ./ElasticSearch/es01/ElasticSearchEnvironment.env
    hostname: qualidade-es01-ces.azores.gov.pt
    build:
      context: .
      dockerfile: ./ElasticSearch/es01/ElasticSearchDockerfile
    networks:
      babel-network:
        ipv4_address: 192.168.1.30
    ports:
      - 9200:9200
      - 9300:9300
    <<: *common-extra-hosts
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es01_data:/usr/share/elasticsearch/data
volumes:
  es01_data:

networks:
  # babel-network:
  #   name: babel-network
  #   driver: bridge
  #   ipam:
  #     driver: default
  #     config:
  #       - subnet: 192.168.1.0/24

  babel-network:
  external: true
  driver: overlay