version: '3'

services:
  load_balancer:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      nginx_network:
        ipv4_address: 192.168.10.10
    depends_on:
      - nginx1
      - nginx2

  nginx1:
    image: nginx
    expose:
      - 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      nginx_network:
        ipv4_address: 192.168.10.11

  nginx2:
    image: nginx
    expose:
      - 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      nginx_network:
        ipv4_address: 192.168.10.12

networks:
  nginx_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
