version: '3.9'
name: mysql
x-common-extra-hosts: &common-extra-hosts
  extra_hosts:
    - "db01-ces.azores.gov.pt:192.168.1.101"
    - "db02-ces.azores.gov.pt:192.168.1.102"
    - "db03-ces.azores.gov.pt:192.168.1.103"    
services:
  mysql-shell:
    container_name: "mysql-shell"  
    tty: true
    env_file:
      - ./config/mysql-shell.env
    networks:
        ces:
            ipv4_address: 192.168.1.199
    <<: *common-extra-hosts
    build: 
        context: .
        dockerfile: ShellDockerfile
    image: mysql-shell
    volumes:
        - ./config/scripts/:/scripts/


networks:
  ces:
    name: ces
    external: true
    driver: overlay