version: '3.5'
name: redis
services:

  redis-node-1:
    container_name: redis-node-1
    image: 'redis:6.0-alpine'
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6373:6373'
    volumes:
      - redis1_data:/var/lib/redis
      - ./node.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis:
        ipv4_address: 172.22.0.2

volumes:
  redis1_data:

networks:
  redis:
    external: true
    driver: overlay
      