version: '3.9'
services:
  fe01:
    build: ./fe01
    ports:
      - "5001:5001"

  fe02:
    build: ./fe02
    ports:
      - "5002:5002"
      
  nginx:
    build: ./nginx
    ports:
      - "443:443"
    depends_on:
      - fe01
      - fe02

networks:
  qld-ces-network:
    driver: bridge    