version: '3.9'
name: backend
services:
  api:
    container_name: api
    image: cesazores/ces:qld_api_1
    ports:
      - 5002:5002
      - 443:443
    restart: always
    networks:
      backend:

networks:
  backend:
    driver: bridge
    #external: true