version: '3.9'
name: mysql
x-common-extra-hosts: &common-extra-hosts
  extra_hosts:
    - "db01-ces.azores.gov.pt:192.168.1.101"
    - "db02-ces.azores.gov.pt:192.168.1.102"
    - "db03-ces.azores.gov.pt:192.168.1.103" 
services:
  mysql-router:
    container_name: "mysql-router"
    env_file:
      - ./conf/Router.env
    networks:
        ces:
          ipv4_address: 192.168.1.100
    <<: *common-extra-hosts
    build: 
        context: .
        dockerfile: RouterDockerfile
    image: mysql-router
    ports:
      - "3306:6446"
    restart: on-failure

networks:
  ces:
    name: ces
    external: true
    driver: overlay