version: "3.9"
name: elasticsearch
services:

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_STACK_VERSION}
    networks:
      elasticsearch:
        ipv4_address: 172.25.1.2
    environment:
      discovery.type: single-node
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      xpack.license.self_generated.type: basic
      bootstrap.memory_lock: true
      xpack.security.enabled: false
      xpack.security.http.ssl.enabled: false
      xpack.security.transport.ssl.enabled: false
      #ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      #xpack.monitoring.enabled: "true"
    ports:
      - 9200:9200
      - 9300:9300
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${KIBANA_STACK_VERSION}
    networks:
      elasticsearch:
        ipv4_address: 172.25.1.3
    depends_on:
      - elasticsearch
    #     condition: service_healthy
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      SERVERNAME: kibana
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: ${KIBANA_PASSWORD}
    mem_limit: ${MEM_LIMIT}
    volumes:
      - kibana_data:/usr/share/kibana/data

volumes:
  es_data:
  kibana_data:

networks:
  elasticsearch:
    driver: overlay
    external: true
      