version: "3.9"
name: elasticsearch
services:

  es01:
    container_name: es01
    hostname: es01
    image: elasticsearch:${ELASTIC_STACK_VERSION}
    networks:
      elasticsearch:
        ipv4_address: 172.25.0.3
    environment:
      #network.host: 0.0.0.0
      cluster.name: ${CLUSTER_NAME}
      discovery.type: single-node
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      xpack.license.self_generated.type: basic
      bootstrap.memory_lock: true
      xpack.security.enabled: false
      xpack.security.http.ssl.enabled: false
      xpack.security.transport.ssl.enabled: false
      #xpack.monitoring.enabled: "true"
      network.publish_host: es01
    ports:
      - 9200:9200
      - 9300:9300
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es01_data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    image: kibana:${KIBANA_STACK_VERSION}
    networks:
      elasticsearch:
        ipv4_address: 172.25.0.4
    depends_on:
      - es01
    #     condition: service_healthy
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://es01:9200
      SERVERNAME: kibana
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: ${KIBANA_PASSWORD}
    mem_limit: ${MEM_LIMIT}
    volumes:
      - kibana_data:/usr/share/kibana/data


volumes:
  es01_data:
  kibana_data:

networks:
  elasticsearch:
    driver: overlay
    external: true
      