version: "3.9"
name: kafka2
x-common-extra-hosts: &common-extra-hosts
  extra_hosts:
    - "kafka1-ces.azores.gov.pt:192.168.1.50"

services:
  kafka2:
    container_name: kafka2-ces.azores.gov.pt
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper1
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092,PLAINTEXT_HOST://kafka1:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      ces:
        ipv4_address: 192.168.1.52
    volumes:
      - kafka2_data:/var/lib/kafka/data

volumes:
  kafka2_data:

networks:
  ces:
    name: ces
    external: true
    driver: overlay