version: "3.9"
name: backend
x-common-extra-hosts: &common-extra-hosts
  extra_hosts:
    - "db01-ces.azores.gov.pt:192.168.1.10"
    - "redis01-ces.azores.gov.pt:192.168.1.20"
    - "es01-ces.azores.gov.pt:192.168.1.30"
    - "es02-ces.azores.gov.pt:192.168.1.31"
    - "kafka1-ces.azores.gov.pt:192.168.1.50"
    - "fe01-ces.azores.gov.pt:192.168.1.80"
    - "api01-ces.azores.gov.pt:192.168.1.90"
    
services:
  backend:
    build:
      context: .
      dockerfile: ./BackendDockerfile
    env_file:
      - ./BackendEnvironment.env
    ports:
      - 443:443
    <<: *common-extra-hosts  
    #mem_limit: ${MEM_LIMIT}
    volumes:
      - backend_data:/api
    restart: always
    networks:
        ces:
            ipv4_address: 192.168.1.90



volumes:
 backend_data:

   
networks:
  ces:
    external: true
    driver: overlay  