version: "3.9"
name: elasticsearch-es02
x-common-extra-hosts: &common-extra-hosts
  extra_hosts:
    - "es01-ces.azores.gov.pt:192.168.1.30"
    - "es02-ces.azores.gov.pt:192.168.1.31"
    
services:
  es02:
    container_name: es02-ces.azores.gov.pt
    env_file:
      - ./ElasticSearch/es02/ElasticSearchEnvironment.env
    hostname: es02-ces.azores.gov.pt
    build:
      context: .
      dockerfile: ./ElasticSearch/es02/ElasticSearchDockerfile
    image: elasticsearch-es02
    networks:
      ces:
        ipv4_address: 192.168.1.31
    ports:
      - 9201:9200
      - 9300:9300
    <<: *common-extra-hosts
    mem_limit: 60129542144
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es02_data:/usr/share/elasticsearch/data
volumes:
  es02_data:

networks:
  ces:
    name: ces
    external: true
    driver: overlay