version: "3.9"
name: "redis"
x-common-extra-hosts: &common-extra-hosts
  extra_hosts:
    - "redis01-ces.azores.gov.pt:192.168.1.20"    
services:
  redis:
    env_file:
      - ./Redis/Redis.env
    networks:
      ces:
        ipv4_address: 192.168.1.20
    container_name: "redis01-ces.azores.gov.pt"
    build:
      context: .
      dockerfile: ./Redis/RedisDockerfile
    image: redis
    ports:
      - 6379:6379
    <<: *common-extra-hosts
    volumes:
      - redis_data:/usr/local/etc/redis
    #Memory limite 14.8GB
    mem_limit: 14884901888
  
volumes:
  redis_data:
   
networks:
  ces:
    name: ces
    external: true
    driver: overlay