version: '3.5'
name: redis
services:

  redis4:
    container_name: redis4
    image: 'redis:6.0-alpine'
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6374:6374'
    volumes:
      - redis4_data:/var/lib/redis
      - ./node4.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis:
        ipv4_address: 172.22.0.6

  redis5:
    container_name: redis5
    image: 'redis:6.0-alpine'
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6375:6375'
    volumes:
      - redis5_data:/var/lib/redis
      - ./node5.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis:
        ipv4_address: 172.22.0.7

  redis6:
    container_name: redis6
    image: 'redis:6.0-alpine'
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6376:6376'
    volumes:
      - redis6_data:/var/lib/redis
      - ./node6.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis:
        ipv4_address: 172.22.0.8

volumes:
  redis4_data:
  redis5_data:
  redis6_data:

networks:
  redis:
    external: true
    driver: overlay