version: "3.9"
name: mysql
x-common-extra-hosts: &common-extra-hosts
  extra_hosts:
    - "db01-ces.azores.gov.pt:192.168.1.101"
    - "db02-ces.azores.gov.pt:192.168.1.102"
    - "db03-ces.azores.gov.pt:192.168.1.103"
services:
  mysql-server-1:
    container_name: "db01-ces.azores.gov.pt"
    env_file:
      - ./MySql/MySql.env
    networks:
        ces:
            ipv4_address: 192.168.1.101
    <<: *common-extra-hosts
    build: 
        context: .
        dockerfile: MySqlDockerfile
    image: mysql
    ports:
      - "3301:3306"
    restart: always
    
networks:
  ces:
    name: ces
    external: true
    driver: overlay