version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
      - 443:443
    volumes:
      - ./app:/usr/share/nginx/html
    networks:
      - qld-ces-network

networks:
  qld-ces-network:
