version: "3.3"
name: mysql
services:
  mysql:
      container_name: mysql
      build: .
      command: ["--default-authentication-plugin=mysql_native_password","--log_bin_trust_function_creators=1", "--lower_case_table_names=1"]
      environment:
        MYSQL_ROOT_PASSWORD: P@ssw0rd
      restart: always
      volumes:
      - mysql_data:/var/lib/mysql
      ports:
      - "3306:3306"

volumes:
  mysql_data:
    driver: local
