version: '3.5'
name: redis
services:

  redis-cluster:
      image: redis:6.0-alpine
      command: redis-cli --cluster create 172.22.0.3:6371 172.22.0.4:6372 172.22.0.5:6373 172.22.0.6:6374 172.22.0.7:6375 172.22.0.8:6376 --cluster-replicas 1 --cluster-yes
      networks:
        redis:
          ipv4_address: 172.22.0.2

  redis1:
    container_name: redis1
    image: redis:6.0-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6371:6371'
    volumes:
      - redis1_data:/var/lib/redis
      - ./node1.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis:
        ipv4_address: 172.22.0.3

  redis2:
    container_name: redis2
    image: redis:6.0-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6372:6372'
    volumes:
      - redis2_data:/var/lib/redis
      - ./node2.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis:
        ipv4_address: 172.22.0.4

  redis3:
    container_name: redis3
    image: redis:6.0-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6373:6373'
    volumes:
      - redis3_data:/var/lib/redis
      - ./node3.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis:
        ipv4_address: 172.22.0.5

volumes:
  redis1_data:
  redis2_data:
  redis3_data:

networks:
  redis:
    external: true
    driver: overlay