version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5002:5002
      - 443:443
    restart: always
    networks:
      - qld_ces_network

networks:
  qld_ces_network:
    driver: overlay
