version: "3.9"
services:
  redis:
    restart: always
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      ces_network:
        #ipv4_address: 192.168.1.120

  zookeeper:
    image: bitnami/zookeeper:3.8.1
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: yes
    healthcheck:
      test: echo stat | nc localhost 2181
      interval: 10s
      timeout: 10s
      retries: 3
    ports:
      - 22181:2181
    networks:
      ces_network:
        #ipv4_address: 192.168.1.120

  kafka1:
    restart: always
    image: bitnami/kafka:3.2.3
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9091
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      BOOTSTRAP_SERVERS: kafka1:9091,kafka2:9092
      ZOOKEEPER: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
    ports:
      - "9091:9091"
    healthcheck:
      test: ps augwwx | egrep [S]upportedKafka
    networks:
      ces_network:
        #ipv4_address: 192.168.1.122
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/var/lib/kafka/data

  kafka2:
    restart: always
    image: bitnami/kafka:3.2.3
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      BOOTSTRAP_SERVERS: kafka1:9091,kafka2:9092
      ZOOKEEPER: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
    ports:
      - "9092:9092"
    healthcheck:
      test: ps augwwx | egrep [S]upportedKafka
    networks:
      ces_network:
        #ipv4_address: 192.168.1.122
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/var/lib/kafka/data
  
  sqlserver:
    restart: always
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
      # - MSSQL_DATA_DIR=/var/opt/sqlserver/data
      # - MSSQL_LOG_DIR=/var/opt/sqlserver/log
      # - MSSQL_BACKUP_DIR=/var/opt/sqlserver/backup
      # - MSSQL_TCP_PORT=1433
    ports:
      - "1433:1433"
    volumes:
      - sqlsystem_data:/var/opt/mssql/
      - sqldata_data:/var/opt/sqlserver/data
      - sqllog_data:/var/opt/sqlserver/log
      - sqlbackup_data:/var/opt/sqlserver/backup
    networks:
      ces_network:
        #ipv4_address: 192.168.1.123
    deploy:
        resources:
            limits:
                memory: 2048M

volumes:
  zookeeper_data:
  kafka_data:
  sqlserver_data:
  sqlsystem_data:
  sqldata_data:
  sqllog_data:
  sqlbackup_data:

networks:
  ces_network:
    # external: true

      