version: "3.9"
services:
  redis:
    restart: always
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - dev-ces-network

  zookeeper:
    restart: always
    image: 'bitnami/zookeeper:3.8.1'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - dev-ces-network

  kafka:
    restart: always
    image: 'bitnami/kafka:3.2.3'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - dev-ces-network
    depends_on:
      - zookeeper
  
  sqlserver:
    restart: always
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
      - MSSQL_DATA_DIR=/var/opt/sqlserver/data
      - MSSQL_LOG_DIR=/var/opt/sqlserver/log
      - MSSQL_BACKUP_DIR=/var/opt/sqlserver/backup
      - MSSQL_TCP_PORT=1433
    ports:
      - "1433:1433"
    volumes:
      - sqlsystem_data:/var/opt/mssql/
      - sqldata_data:/var/opt/sqlserver/data
      - sqllog_data:/var/opt/sqlserver/log
      - sqlbackup_data:/var/opt/sqlserver/backup
    networks:
      - dev-ces-network
    deploy:
        resources:
            limits:
                memory: 2048M

volumes:
  zookeeper_data:
  kafka_data:
  sqlserver_data:
  sqlsystem_data:
  sqldata_data:
  sqllog_data:
  sqlbackup_data:

networks:
  dev-ces-network:
    driver: bridge